main/src/JAG.DevTest2019.WebHost/Models/LeadResultViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JAG.DevTest2019.Host.Models
{
    public class LeadResultViewModel
    {
        public long LeadId { get; set; }

        public bool IsSuccessful { get; set; }

        public string Message { get; set; }
    }
}

main/src/JAG.DevTest2019.WebHost/Models/LeadViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JAG.DevTest2019.Host.Models
{
    public class LeadViewModel
    {
        public LeadViewModel()
        {
            Results = new LeadResultViewModel();
        }

        public string TrackingCode { get; }

        [Display(Name = "Select your gender?")]
        public string Gender { get; set; }

        [Display(Name = "Select your language?")]
        public string Language { get; set; }

        [Display(Name = "Select your blood type?")]
        public string BloodType { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Surname")]
        public string Surname { get; set; }

        [Display(Name = "Email Address")]
        public string EmailAddress { get; set; }

        [Display(Name = "Contact Number")]
        public virtual string ContactNumber { get; set; }

        public List<SelectListItem> Genders { get; } = new List<SelectListItem>()
        {
            new SelectListItem()  {Text="Male", Value = "Male"},
            new SelectListItem()  {Text="Female", Value = "Female"},
        };

        public List<SelectListItem> Languages { get; } = new List<SelectListItem>()
        {
            new SelectListItem()  {Text="English", Value = "English"},
            new SelectListItem()  {Text="Afrikaans", Value = "Afrikaans"},
            new SelectListItem()  {Text="Zulu", Value = "Zulu"},
            new SelectListItem()  {Text="Xhosa", Value = "Xhosa"},
            new SelectListItem()  {Text="Sesotho ", Value = "Sesotho"},
        };

        public List<SelectListItem> BloodTypes { get; } = new List<SelectListItem>()
        {
            new SelectListItem()  {Text="O+", Value = "O+"},
            new SelectListItem()  {Text="O-", Value = "O-"},
            new SelectListItem()  {Text="A+", Value = "A+"},
            new SelectListItem()  {Text="A-", Value = "A-"},
            new SelectListItem()  {Text="B+", Value = "B+"},
            new SelectListItem()  {Text="B-", Value = "B-"},
            new SelectListItem()  {Text="AB+", Value = "AB+"},
            new SelectListItem()  {Text="AB-", Value = "AB-"},
        };

        public LeadResultViewModel Results { get; set; }
    }
}

main/src/JAG.DevTest2019.WebHost/Controllers/LeadController.cs
using JAG.DevTest2019.Host.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web;
using System.Web.Mvc;

namespace JAG.DevTest2019.Host.Controllers
{
    public class LeadController : Controller
    {
        public ActionResult Index()
        {
            return View(new LeadViewModel());
        }

        public ActionResult SubmitLead(LeadViewModel model)
        {
            //TODO: 6. Call the WebAPI service here & pass results to UI

            LeadViewModel result = new LeadViewModel()
            {
                Results = new LeadResultViewModel()
                {
                    LeadId = new Random().Next(),
                    IsSuccessful = true,
                    Message = "Thank you for submitting your details"
                }
            };

            return View("Index",result);
        }
    }
}

main/src/JAG.DevTest2019.WebHost/Views/Lead/Index.cshtml
@{
    Layout = "~/Views/shared/_LeadLayout.cshtml";
    ViewBag.Title = "Page title";
}
@using JAG.DevTest2019.Host.Models
@model LeadViewModel
  
@section Meta{
    <meta name="description" content="Default site" />
    <meta name="keywords" content="Default" />
}

<section id="quote" class="main-banner" style="background-image: url(/Content/Images/Banners/car-insurance.jpg)">
    <div class="slant-left col-md-9 pull-left">
        <div class="col-md-8 col-md-offset-2">
            <div class="capture-form">
                <h1 class="text-center">Insurance</h1>
                <h4>Don’t pay too much, find the best insurance quotes and start saving today!</h4>
                @using (Html.BeginForm("SubmitLead", "Lead", FormMethod.Post, new { id = "frmsubmit" }))
                {
                    @Html.AntiForgeryToken();
                    <div class="col-md-12">
                        <p>
                            <input type="hidden" value="@Model.TrackingCode" id="hdnTrackingCode" />

                            My name is @Html.TextBoxFor(model => model.FirstName, new { @placeholder = Html.DisplayNameFor(model => model.FirstName) }) @Html.TextBoxFor(model => model.Surname, new { @placeholder = Html.DisplayNameFor(model => model.Surname) })
                            You can contact me at @Html.TextBoxFor(model => model.EmailAddress, new { @placeholder = Html.DisplayNameFor(model => model.EmailAddress) }) or @Html.TextBoxFor(model => model.ContactNumber, new { @placeholder = Html.DisplayNameFor(model => model.ContactNumber) })
                            to help me save on insurance
                            I am @Html.DropDownListFor(model => model.Gender, Model.Genders, "Gender") and my language preference is
                            @Html.DropDownListFor(model => model.Language, Model.Languages, "Language")
                            and my blood type is @Html.DropDownListFor(model => model.Language, Model.BloodTypes, "BloodType")
                        </p>
                    </div>
                    <div class="clearfix"></div>

                    <div class="col-md-12 text-center">
                        <button type="submit" id="btnSubmit" class="orange-button">Get Quotes Now</button>
                    </div>
                }
                @if (Model.Results != null &&
                    Model.Results.IsSuccessful)
                {
                    <div class="col-md-12 text-center">
                        <img src="~/Content/Images/Products/new-success.png" height="24px"/>
                        @Html.ValueFor(model => model.Results.Message)
                    </div>
                }

                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</section>
<div class="clearfix"></div>
<div class="container benefits-padding text-center">
    <h2>Benefits</h2>
    <div class="benefits-cols">
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-save.png"/>
            <p>People saved on insurance</p>
        </div>
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-calling.png"/>
            <p>99.99% were called in under 5 minutes</p>
        </div>
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-success.png"/>
            <p>96% believe these stats</p>
        </div>
        <div class="col-md-3 text-center text-instructions">
            <img src="~/Content/Images/Products/new-clients.png"/>
            <p>Over 6,000,000 queries serviced</p>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<div id="quote" class="testimonial-banner" style="background-image: url('../../Content/Images/Banners/best-car-insurance.jpg');">
    <div class="slant-right col-md-9 pull-right">
        <div class="col-md-6 col-md-offset-3 testimonials text-center">
            <b>Getting the lowest insurance quote has never been so easy:</b>
            <p>
                <b>Joe Blogs (26 years)</b><br/><br/>
                Telsa model x <br />
                Was paying R999,999.99<br />
                Now paying R99.99
            </p>
            <h2 class="highlight">Insurance saving of {lots of %}</h2>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
</div>
<div class="clearfix"></div>
<div class="container-blue">
    <div class="col-md-6 col-md-offset-3 text-center">
        <h1>Get a quote and</h1>
        <h1 class="green">start saving now</h1>
        <p>Get in touch to receive insurance quotes from South Africa’s top insurance companies. Getting the lowest insurance premiums has never been so easy.</p>
        <a id="lnkGetQuote" href="#quote" class="orange-button">Get a quote now</a>
    </div>
    <div class="clearfix"></div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#lnkLead').addClass('activeMenu');
        })
    </script>
}

main/src/JAG.DevTest2019.WebHost/Views/Shared/_LeadLayout.cshtml
@using System.Web.Mvc

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/favicon.ico" rel="shortcut icon">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:500,600,800" rel="stylesheet">
    <title>JAG Dev Test: @ViewBag.Title</title>
    @RenderSection("Meta", required: false)

    <!-- Styles
    ================================================== -->
    @Styles.Render("~/bundles/css")
    <link rel="stylesheet" href="~/Content/Newcustom.css">
    <style>
        .async-hide {
            opacity: 0 !important
        }
    </style>

    <!--[if IE]>
    <link rel="stylesheet" href="../Content/IEfixes.css">
    <![endif]-->
    <!--[if lt IE 9]>
    <link rel="stylesheet" href="~/Content/ltIEfixes.css">
    <![endif]-->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltips and media queries -->
    <!--[if lt IE 9]>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div class="pre-header">
        <div class="container">
            <div class="col-md-12 pull-right number text-right">
                Need help? <a href="tel:+27113266761">011 326 6761</a>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clear"></div>
    </div>
    <nav class="navbar navbar-default" role="navigation">
        <div class="header container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a id="hypLogo" href="/">
                    <img src="~/Content/Images/logo.png" style="height:50px">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a id="lnkHome" href="/">Home</a></li>
                    <li><a id="lnkLead" href="/Lead">Leads</a></li>
                </ul>
            </div>
            <div class="clearfix"></div>
        </div>
    </nav>
    @RenderBody()
    <div class="clearfix"></div>

    <!-- JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- IE8 support of jQuery -->
    <!--[if lt IE 9]>
    <script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>
    <![endif]-->
    <!--[if gte IE 9]><!-->
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    <!--<![endif]-->
    <!--[if !IE]>
    <!--LeadBot-->
    @*<script type="text/javascript" src="https://popupwidget.leadflip.ai"> </script>*@
    <!--<![endif]-->

    @Scripts.Render("~/bundles/js")
    @RenderSection("Scripts", required: false)

</body>
</html>